import type { Recipe } from '../types'

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'r1',
    name: 'Chicken & Rice Power Bowl',
    description: 'High-protein classic. Juicy chicken breast over fluffy brown rice with steamed broccoli.',
    emoji: '🍗',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    tags: ['high-protein', 'bulk', 'lunch', 'dinner'],
    macrosPerServing: { calories: 480, protein: 48, carbs: 42, fat: 8 },
    ingredients: [
      { id: 'i1', name: 'Chicken breast', amount: 800, unit: 'g', macros: { calories: 880, protein: 160, carbs: 0, fat: 20 } },
      { id: 'i2', name: 'Brown rice', amount: 300, unit: 'g dry', macros: { calories: 1050, protein: 24, carbs: 216, fat: 6 } },
      { id: 'i3', name: 'Broccoli', amount: 400, unit: 'g', macros: { calories: 136, protein: 12, carbs: 24, fat: 2 } },
      { id: 'i4', name: 'Olive oil', amount: 2, unit: 'tbsp', macros: { calories: 240, protein: 0, carbs: 0, fat: 28 } },
      { id: 'i5', name: 'Garlic powder', amount: 1, unit: 'tsp', macros: { calories: 10, protein: 0, carbs: 2, fat: 0 } },
      { id: 'i6', name: 'Salt & pepper', amount: 1, unit: 'pinch', macros: { calories: 0, protein: 0, carbs: 0, fat: 0 } },
    ],
    steps: [
      { id: 's1', instruction: 'Rinse brown rice and cook with 2:1 water ratio.', timerSeconds: 1800 },
      { id: 's2', instruction: 'Season chicken breasts with garlic powder, salt, and pepper.', timerSeconds: 0 },
      { id: 's3', instruction: 'Heat olive oil in a pan over medium-high. Cook chicken 6–7 min per side.', timerSeconds: 420 },
      { id: 's4', instruction: 'Steam broccoli florets until tender-crisp.', timerSeconds: 300 },
      { id: 's5', instruction: 'Slice chicken and divide everything into 4 containers.', timerSeconds: 0 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r2',
    name: 'Greek Yogurt Parfait',
    description: 'Quick high-protein breakfast. Creamy yogurt layered with berries and granola.',
    emoji: '🫐',
    servings: 3,
    prepMinutes: 5,
    cookMinutes: 0,
    tags: ['high-protein', 'breakfast', 'quick'],
    macrosPerServing: { calories: 290, protein: 22, carbs: 38, fat: 5 },
    ingredients: [
      { id: 'i7', name: 'Greek yogurt (0%)', amount: 600, unit: 'g', macros: { calories: 360, protein: 60, carbs: 18, fat: 3 } },
      { id: 'i8', name: 'Mixed berries', amount: 300, unit: 'g', macros: { calories: 150, protein: 3, carbs: 36, fat: 0 } },
      { id: 'i9', name: 'Granola', amount: 120, unit: 'g', macros: { calories: 540, protein: 12, carbs: 84, fat: 12 } },
      { id: 'i10', name: 'Honey', amount: 3, unit: 'tsp', macros: { calories: 60, protein: 0, carbs: 18, fat: 0 } },
    ],
    steps: [
      { id: 's6', instruction: 'Divide Greek yogurt evenly into 3 jars or containers.', timerSeconds: 0 },
      { id: 's7', instruction: 'Top each with mixed berries and granola.', timerSeconds: 0 },
      { id: 's8', instruction: 'Drizzle 1 tsp honey over each parfait. Seal and refrigerate.', timerSeconds: 0 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r3',
    name: 'Lentil & Veggie Soup',
    description: 'Hearty plant-based soup packed with fiber and protein. Makes a huge batch.',
    emoji: '🍲',
    servings: 6,
    prepMinutes: 15,
    cookMinutes: 40,
    tags: ['vegan', 'bulk', 'lunch', 'dinner', 'high-protein'],
    macrosPerServing: { calories: 310, protein: 18, carbs: 48, fat: 4 },
    ingredients: [
      { id: 'i11', name: 'Red lentils', amount: 400, unit: 'g', macros: { calories: 1400, protein: 96, carbs: 240, fat: 8 } },
      { id: 'i12', name: 'Diced tomatoes (canned)', amount: 800, unit: 'g', macros: { calories: 160, protein: 8, carbs: 32, fat: 0 } },
      { id: 'i13', name: 'Carrots', amount: 3, unit: 'medium', macros: { calories: 105, protein: 3, carbs: 24, fat: 0 } },
      { id: 'i14', name: 'Celery', amount: 3, unit: 'stalks', macros: { calories: 30, protein: 1, carbs: 6, fat: 0 } },
      { id: 'i15', name: 'Onion', amount: 1, unit: 'large', macros: { calories: 60, protein: 2, carbs: 14, fat: 0 } },
      { id: 'i16', name: 'Vegetable broth', amount: 1500, unit: 'ml', macros: { calories: 60, protein: 0, carbs: 12, fat: 0 } },
      { id: 'i17', name: 'Cumin', amount: 2, unit: 'tsp', macros: { calories: 16, protein: 1, carbs: 2, fat: 1 } },
    ],
    steps: [
      { id: 's9', instruction: 'Dice onion, carrots, and celery. Sauté in a large pot with olive oil for 5 min.', timerSeconds: 300 },
      { id: 's10', instruction: 'Add cumin and stir for 1 minute until fragrant.', timerSeconds: 60 },
      { id: 's11', instruction: 'Add rinsed lentils, diced tomatoes, and vegetable broth. Stir to combine.', timerSeconds: 0 },
      { id: 's12', instruction: 'Bring to a boil, then simmer uncovered for 30 minutes until lentils are soft.', timerSeconds: 1800 },
      { id: 's13', instruction: 'Season with salt and pepper. Divide into 6 containers.', timerSeconds: 0 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r4',
    name: 'Overnight Oats',
    description: 'No-cook breakfast prep. Creamy, filling, and customizable.',
    emoji: '🥣',
    servings: 5,
    prepMinutes: 10,
    cookMinutes: 0,
    tags: ['vegetarian', 'breakfast', 'quick', 'bulk'],
    macrosPerServing: { calories: 380, protein: 16, carbs: 58, fat: 9 },
    ingredients: [
      { id: 'i18', name: 'Rolled oats', amount: 500, unit: 'g', macros: { calories: 1900, protein: 65, carbs: 325, fat: 30 } },
      { id: 'i19', name: 'Milk (whole)', amount: 1000, unit: 'ml', macros: { calories: 620, protein: 32, carbs: 48, fat: 32 } },
      { id: 'i20', name: 'Chia seeds', amount: 50, unit: 'g', macros: { calories: 240, protein: 8, carbs: 16, fat: 16 } },
      { id: 'i21', name: 'Maple syrup', amount: 5, unit: 'tbsp', macros: { calories: 300, protein: 0, carbs: 78, fat: 0 } },
      { id: 'i22', name: 'Vanilla extract', amount: 1, unit: 'tsp', macros: { calories: 12, protein: 0, carbs: 1, fat: 0 } },
    ],
    steps: [
      { id: 's14', instruction: 'Mix oats, chia seeds, milk, maple syrup, and vanilla in a large bowl.', timerSeconds: 0 },
      { id: 's15', instruction: 'Divide evenly into 5 jars. Seal and refrigerate overnight.', timerSeconds: 0 },
      { id: 's16', instruction: 'In the morning, stir well and add fresh toppings like fruit or nut butter.', timerSeconds: 0 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'r5',
    name: 'Salmon & Asparagus Sheet Pan',
    description: 'Omega-3 rich dinner. Everything roasts together on one pan — zero fuss.',
    emoji: '🐟',
    servings: 2,
    prepMinutes: 8,
    cookMinutes: 20,
    tags: ['high-protein', 'low-carb', 'dinner', 'quick'],
    macrosPerServing: { calories: 420, protein: 42, carbs: 10, fat: 24 },
    ingredients: [
      { id: 'i23', name: 'Salmon fillets', amount: 400, unit: 'g', macros: { calories: 560, protein: 72, carbs: 0, fat: 28 } },
      { id: 'i24', name: 'Asparagus', amount: 300, unit: 'g', macros: { calories: 60, protein: 6, carbs: 12, fat: 0 } },
      { id: 'i25', name: 'Lemon', amount: 1, unit: 'whole', macros: { calories: 17, protein: 1, carbs: 5, fat: 0 } },
      { id: 'i26', name: 'Olive oil', amount: 2, unit: 'tbsp', macros: { calories: 240, protein: 0, carbs: 0, fat: 28 } },
      { id: 'i27', name: 'Garlic cloves', amount: 3, unit: 'cloves', macros: { calories: 15, protein: 1, carbs: 3, fat: 0 } },
      { id: 'i28', name: 'Dill (dried)', amount: 1, unit: 'tsp', macros: { calories: 5, protein: 0, carbs: 1, fat: 0 } },
    ],
    steps: [
      { id: 's17', instruction: 'Preheat oven to 200°C / 400°F.', timerSeconds: 0 },
      { id: 's18', instruction: 'Toss asparagus with olive oil, minced garlic, salt, and pepper. Spread on sheet pan.', timerSeconds: 0 },
      { id: 's19', instruction: 'Place salmon fillets on the pan. Drizzle with remaining olive oil and sprinkle with dill.', timerSeconds: 0 },
      { id: 's20', instruction: 'Roast for 18–20 minutes until salmon flakes easily.', timerSeconds: 1200 },
      { id: 's21', instruction: 'Squeeze fresh lemon over everything and serve or pack into containers.', timerSeconds: 0 },
    ],
    createdAt: new Date().toISOString(),
  },
]
