/**
 * One file to paste.
 *
 * The `notify` function is two files: the plumbing, and the decisions about
 * what to send, which live apart so they can be tested under vitest with the
 * rest of the app. That split is right for the repository and wrong for the
 * person deploying, who has no Supabase CLI and is pasting into a dashboard
 * editor where a second file at a relative path is a thing that goes wrong
 * quietly.
 *
 * So this flattens the two into one, and `verify` fails if the flattened copy
 * has drifted from its sources. Without that check the pasted file would go
 * stale the first time anybody edited the real one, and nobody would find out
 * until a notification did the wrong thing.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SHARED = resolve(ROOT, 'supabase/functions/_shared/notify.ts')
const ENTRY = resolve(ROOT, 'supabase/functions/notify/index.ts')
const OUT = resolve(ROOT, 'supabase/functions/notify/deploy.ts')

const HEADER = `// Generated by scripts/build-function.ts. Do not edit.
//
// This is supabase/functions/notify/index.ts with _shared/notify.ts inlined,
// so the whole function is one file to paste into the Supabase dashboard
// editor. Edit the sources, then run: npm run function:build
`

export function flatten(shared: string, entry: string): string {
  // The shared file has no imports by design, so inlining it is a paste. Its
  // exports stay: a Deno module is allowed them, and nothing here imports it.
  const body = shared.trimEnd()

  // Take out the import of the file that is now above, and nothing else.
  const withoutImport = entry.replace(
    /import\s*\{[^}]*\}\s*from\s*'\.\.\/_shared\/notify\.ts'\n/,
    '',
  )

  if (withoutImport === entry) {
    throw new Error('the import of ../_shared/notify.ts was not found, so nothing was inlined')
  }

  return `${HEADER}\n${body}\n\n${withoutImport.trimStart()}`
}

const result = flatten(readFileSync(SHARED, 'utf8'), readFileSync(ENTRY, 'utf8'))

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {
    console.error('deploy.ts is missing. Run: npm run function:build')
    process.exit(1)
  }
  if (current !== result) {
    console.error('deploy.ts is out of date with its sources. Run: npm run function:build')
    process.exit(1)
  }
  console.log('the single file copy of notify matches its sources')
} else {
  writeFileSync(OUT, result)
  console.log(`wrote ${OUT.replace(ROOT + '/', '')}, ${result.split('\n').length} lines`)
}
