import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FOODS } from '../src/data/foods.js'
import { DISHES } from '../src/data/dishes.js'
import { MEAL_RECIPES } from '../src/data/generated/mealRecipes.js'
import { buildContext } from '../src/lib/nutrition.js'
import { classify } from '../src/lib/classify.js'
import { CATEGORY_LABELS } from '../src/lib/dishCategories.js'

/**
 * Assigns every shipped recipe a dish category and its derivable quick filters.
 *
 * Run: npx tsx scripts/classify-recipes.ts
 *
 * The result is written out rather than computed at startup, for two reasons:
 * it is data about a recipe and belongs next to the recipe, and it has to be
 * editable — the moment you disagree with one of these, your version has to
 * win. Re-running overwrites the file, so edit the rules in lib/classify.ts
 * rather than the output.
 *
 * The dietician's own .docx files are not in the repository, so this reads the
 * already-generated recipes rather than the sources. That also means it can be
 * re-run any time the rules change, which is the point.
 */

const HERE = dirname(fileURLToPath(import.meta.url))
const recipes = [...DISHES, ...MEAL_RECIPES]
const ctx = buildContext(FOODS, recipes)

const rows = recipes.map((r) => [r.id, classify(r, ctx)] as const)

const file = `// Generated by scripts/classify-recipes.ts — do not edit by hand.
// Change the rules in src/lib/classify.ts and re-run.
import type { DishCategory, QuickFilter } from '../../types'

export interface RecipeClassification {
  category: DishCategory
  quickFilters: QuickFilter[]
}

export const RECIPE_CLASSIFICATION: Record<string, RecipeClassification> = {
${rows.map(([id, c]) =>
  `  ${JSON.stringify(id)}: { category: ${JSON.stringify(c.category)}, quickFilters: ${JSON.stringify(c.quickFilters)} },`,
).join('\n')}
}
`

writeFileSync(resolve(HERE, '../src/data/generated/classification.ts'), file)

// A summary, so a change in the rules is visible rather than buried in a diff.
const byCategory = new Map<string, number>()
const byFilter = new Map<string, number>()
for (const [, c] of rows) {
  byCategory.set(c.category, (byCategory.get(c.category) ?? 0) + 1)
  for (const f of c.quickFilters) byFilter.set(f, (byFilter.get(f) ?? 0) + 1)
}

console.log(`${rows.length} recipes classified into ${byCategory.size} of ${Object.keys(CATEGORY_LABELS).length} categories\n`)
for (const [c, n] of [...byCategory].sort((a, b) => b[1] - a[1])) {
  console.log(String(n).padStart(4), c)
}
console.log('\nquick filters')
for (const [f, n] of [...byFilter].sort((a, b) => b[1] - a[1])) {
  console.log(String(n).padStart(4), f)
}
